layout_spectrum: 0.7527822693809867
typography_spectrum: 0.8145092411432415
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6222901078872383
  lightness: 0.0034443794284015894
  saturation: 0.07229659962467849
  rhythmicContrast: 0.5004080939106643
name: La Calamine
favicon: null
title: Die 200-jährige Geschichte Kelmis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
