typography_spectrum: 0.8145092411432415
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6222901078872383
  lightness: 0.0034443794284015894
  saturation: 0.07229659962467849
  rhythmicContrast: 0.5004080939106643
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7527822693809867
analytics:
  google: null
  facebook: null
  twitter: null
name: La Calamine
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Die Gemeinde Kelmis
    id: b4e6abb5-47ad-4372-9416-0b39d0226d87
    type: content
  - name: Der Kasinoweiher
    id: 8ae3f5a3-43e2-4930-995f-cf05a5d723cc
    type: content
favicon: null
title: Die 200-jährige Geschichte Kelmis
purpose: []
